---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources: 
- ./namespace.yaml
- ./rbac.yaml

helmGlobals:
  chartHome: ../../../../helm/charts

helmCharts:
  - name: crossplane
    releaseName: crossplane
    repo: https://charts.crossplane.io/stable
    namespace: crossplane-system
    valuesFile: values.yaml

  - name: ess-plugin-vault
    releaseName: ess-plugin-vault
    #repo: oci://xpkg.upbound.io/crossplane-contrib/ess-plugin-vault
    namespace: crossplane-system
    valuesFile: ess-values.yaml    