---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/acm-operator/
commonAnnotations:
  argocd.argoproj.io/sync-options: Delete=false

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: "release-2.7"
    target:
      kind: Subscription
