---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/metallb-configuration/


patches:
  - patch: |-
      - op: replace
        path: /spec/addresses/0
        value: 10.1.196.100-10.1.196.110
    target:
      kind: IPAddressPool
      name: main