---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/nfs-provisioner-operator.openshift-operators: ''
  name: nfs-provisioner-operator
  namespace: openshift-operators
spec:
  channel: <REPLACE>
  installPlanApproval: Automatic
  name: nfs-provisioner-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
