apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - ../../../bases/openshift-virtualization-operator/
commonAnnotations:
  argocd.argoproj.io/sync-options: Delete=false

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: "stable"
    target:
      kind: Subscription