apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
 name: cluster-worker-nodes
 namespace: openshift-storage
spec:
 storage:
   deviceClasses:
   - name: vg2
     default: false
     deviceSelector:
       paths: 
       - /dev/sdb
       - /dev/sr0
     thinPoolConfig:
       name: thin-pool-1
       sizePercent: 90
       overprovisionRatio: 10
     nodeSelector:
       nodeSelectorTerms:
       - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values: 
           - pool4-compute1.practice.redhat.com
           - pool4-compute2.practice.redhat.com