---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - ./cluster.yaml
  - ./csi-cephfsplugin-snapclass-vsclass.yaml
  - ./csi-nfsplugin-snapclass-vsclass.yaml
  - ./csi-rbdplugin-snapclass-vsclass.yaml
  - ./rook-ceph-block-sc.yaml
  - ./rook-ceph-mgr-dashboard-route.yaml
  - ./rook-ceph-nfs.yaml
  - ./rook-ceph-filesystem.yaml
  - ./file-storage-class.yaml
  - ./nfs-storage-class.yaml
  - ./object-storage.yaml
  - ./object-storage-storage-class.yaml


