---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sensor
spec:
  commonName: "SENSOR_SERVICE: 00000000-0000-0000-0000-000000000000"
  secretName: sensor-tls
  usages:
    - client auth
    - server auth
  dnsNames:
    - sensor.stackrox
    - sensor.stackrox.svc
    - sensor-webhook.stackrox.svc
  issuerRef:
    name: acs-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: collector
spec:
  commonName: "COLLECTOR_SERVICE: 00000000-0000-0000-0000-000000000000"
  secretName: collector-tls
  usages:
    - client auth
    - server auth    
  dnsNames:
    - collector.stackrox
    - collector.stackrox.svc      
  issuerRef:
    name: acs-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admission-control
spec:
  commonName: "ADMISSION_CONTROL_SERVICE: 00000000-0000-0000-0000-000000000000"
  secretName: admission-control-tls
  dnsNames:
    - admission-control.stackrox
    - admission-control.stackrox.svc  
  usages:
    - client auth
    - server auth      
  issuerRef:
    name: acs-ca-issuer
    kind: Issuer
    group: cert-manager.io    
