---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: central-default-tls-cert
  namespace: stackrox
spec:
  secretName: central-default-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - <REPLACE>
