---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - namespace.yaml
  - central.yaml
  - patches-rbac.yaml
  - patches.yaml
  - acs-ca-secret.yaml
  - link.yaml
  - acs-config.yaml
  - issuer.yaml
  - bundle-certificates.yaml
