kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acs-patches-rbac
  namespace: stackrox
subjects:
  - kind: ServiceAccount
    name: default
    namespace: stackrox # namespace:operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io