apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: crossplane-secrets
spec:
  authentication: 
    path: kubernetes
    role: policy-admin
  type: kv
  path: ""
  options:
    version: "2"