apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: crossplane-secrets
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  policy: |
    path "crossplane-secrets/data/*" {
        capabilities = ["create", "read", "update", "delete"]
    }
    path "crossplane-secrets/metadata/*" {
        capabilities = ["create", "read", "update", "delete"]
    }