kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ess-plugin-vault.fullname" . }}
  labels:
    {{- include "ess-plugin-vault.labels" . | nindent 4 }}
rules:
  - apiGroups: ["secrets.crossplane.io"]
    resources: ["vaultconfigs"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ess-plugin-vault.fullname" . }}
  labels:
    {{- include "ess-plugin-vault.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ess-plugin-vault.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ess-plugin-vault.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}