apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
 name: cluster-local-storage
 namespace: openshift-storage
spec:
 storage:
   deviceClasses:
   - name: vg1
     default: false
     deviceSelector:
       paths: []
     thinPoolConfig:
       name: thin-pool-1
       sizePercent: 90
       overprovisionRatio: 10
     nodeSelector:
       nodeSelectorTerms:
       - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values: []