apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-workspaces
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    imagePuller:
      enable: true
    metrics:
      enable: true
  containerRegistry: {}
  devEnvironments:
    startTimeoutSeconds: 300
    secondsOfRunBeforeIdling: -1
    maxNumberOfWorkspacesPerUser: -1
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    defaultNamespace:
      autoProvision: true
      template: <username>-workspace
    secondsOfInactivityBeforeIdling: 1800
    storage:
      perUserStrategyPvcConfig:
        storageClass: rook-cephfs
      perWorkspaceStrategyPvcConfig:
        storageClass: rook-cephfs
      pvcStrategy: per-user
  gitServices: {}
  networking: {}