---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/acs-secured-configuration/

commonAnnotations:
  argocd.argoproj.io/sync-options: Delete=false

patches:
  - patch: |-
      - op: replace
        path: /spec/clusterName
        value: "pool4"
      - op: replace
        path: /spec/centralEndpoint
        value: "central-stackrox.apps.pool2.practice.redhat.com:443"
    target:
      kind: SecuredCluster

     

