---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:  
  - ../../../bases/kube-ops-view/

patches:
  - patch: |-
      - op: replace
        path: /spec/href
        value: "https://kube-ops-view-kube-ops-view.apps.pool2.practice.redhat.com/"
    target:
      kind: ConsoleLink