apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ .Release.Name }}-aro
  annotations:
    crossplane.io/external-name: myworkspace
spec:
  forProvider:
    # Use any module source supported by terraform init -from-module.
    source: Remote
    module: https://github.com/raffaelespazzoli/openshift-iac-multicluster/terraform/aro
    # Variables can be specified inline as a list of key-value pairs or as an json object, or loaded from a ConfigMap or Secret.
    vars:
    - key: name
      value: {{ .Release.Name }}-aro
    - key: location
      value: {{ .Values.location }}
    - key: resource_group_id
      value: 
    - key: client_id
      value:    
    - key: client_secret
      value:          
    - key: master_subnet_id
      value:
    - key: worker_subnet_id
      value:
    - key: api_server_visibility
      value: {{ .Values.api_server_visibility }}
    - key: ingress_visibility
      value: {{ .Values.ingress_visibility }}
  # All Terraform outputs are written to the connection secret.
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-example-inline