---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ .Release.Name }}-firewall-subnet
  labels:
    {{- include "aro-provisioning.labels" . | nindent 4 }}    
spec:
  forProvider:
    privateLinkServiceNetworkPoliciesEnabled: false
    addressPrefixes:
      - {{ .Values.firewallSubnet }}
    resourceGroupName: {{ .Values.ResourceGroup }}
    virtualNetworkNameRef:
      name: {{ .Release.Name }}-aro-vnet-{{ .Values.location }}
---
apiVersion: network.azure.upbound.io/v1beta1
kind: PublicIP
metadata:
  name: {{ .Release.Name }}-fw-ip
  labels:
    {{- include "aro-provisioning.labels" . | nindent 4 }}   
spec:
  forProvider:
    location: {{ .Values.location }}
    resourceGroupName: {{ .Values.ResourceGroup }}   
    sku: Standard
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Firewall
metadata:
  name: {{ .Release.Name }}-aro-private
  labels:
    {{- include "aro-provisioning.labels" . | nindent 4 }}   
spec:
  forProvider:
    ipConfiguration:
      - name: fw-config
        publicIpAddressIdRef:
          name: {{ .Release.Name }}-fw-ip
        subnetIdRef:
          name: {{ .Release.Name }}-firewall-subnet
    location: {{ .Values.location }}
    resourceGroupName: {{ .Values.ResourceGroup }}
---
apiVersion: network.azure.upbound.io/v1beta1
kind: FirewallNetworkRuleCollection
metadata:
  name: {{ .Release.Name }}-aro-private
  labels:
    {{- include "aro-provisioning.labels" . | nindent 4 }}  
spec:
  forProvider:
    action: Allow
    azureFirewallName: {{ .Release.Name }}-aro-private
    priority: 100
    resourceGroupName: {{ .Values.ResourceGroup }}
    rule:
      - destinationAddresses:
          - "*"
        destinationPorts:
          - 1-65535
        name: allow-all
        protocols:
          - Any
        sourceAddresses:
          - "*"         