---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-config-operator 
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops   
