---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-config-operator 
  namespace: vault-config-operator 
spec:
  channel: <REPLACE>
  installPlanApproval: Automatic
  name: vault-config-operator 
  source: community-operators
  sourceNamespace: openshift-marketplace

