---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/namespace-configuration-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: alpha
    target:
      kind: Subscription
