apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  annotations:
    managedcluster-import-controller.open-cluster-management.io/keeping-auto-import-secret: ""  
stringData:
  # the following value to specify the retry times when your cluster failed to import
  autoImportRetry: "30"
type: Opaque