apiVersion: batch/v1
kind: CronJob
metadata:
  name: creds-renew
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: creds-renew
            image: registry.redhat.io/openshift4/ose-cli:latest
            envFrom:
            - secretRef:
                name: rosa-creds
            env:
            - name: kube
              value: "/tmp/kubeconfig"           
            command: 
            - /bin/bash
            - -c
            - | 
              oc --kubeconfig=${kube} login --insecure-skip-tls-verify=true -u ${username} -p ${password} ${apiurl}
              export kubeconfig=$(cat ${kube} | base64 -w0)
              oc patch secret auto-import-secret -p '{"data":{"kubeconfig":"'"${kubeconfig}"'"}}' -n rosa-decl
              sleep infinity
          restartPolicy: OnFailure