apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rosa-decl

resources:
- ./namespace.yaml
- ./rosa.yaml

# helmGlobals:
#   chartHome: ../../../../helm/charts

# helmCharts:
#   - name: aro-provisioning
#     releaseName: aro-decl
#     namespace: aro-decl
#     valuesInline:
#       resourceGroup: openenv-hcp4p