apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rosa-decl

resources:
- ./namespace.yaml
- ./rosa.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: availability-zones
  files:
    - availabilityZones=availabilityZones.json


# helmGlobals:
#   chartHome: ../../../../helm/charts

# helmCharts:
#   - name: aro-provisioning
#     releaseName: aro-decl
#     namespace: aro-decl
#     valuesInline:
#       resourceGroup: openenv-hcp4p