apiVersion: crossplane.redhat-cop.com/v1alpha1
kind: Rosa
metadata: 
  name: rosa-decl
spec:
  region: us-east-1
  availabilityZones:
    configMapName: availability-zones
    key: availabilityZones
  adminSecret:
    secretName: cluster-admin
    key: admin-json   