apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: rosa-creds
spec:
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: crossplane
        serviceAccount:
          name: default
      name: rosacreds
      path: crossplane-secrets/data/rosa-tf
  output:
    name: rosa-creds
    stringData:
      username: '{{ .rosacreds.username }}'
      password: '{{ .rosacreds.password }}'
      apiurl: '{{ .rosacreds.api_url }}'
    type: Opaque
    annotations:
      managedcluster-import-controller.open-cluster-management.io/keeping-auto-import-secret: ""    
  refreshPeriod: 3m0s