apiVersion: crossplane.redhat-cop.com/v1alpha1
kind: Rosa
metadata: 
  name: rosa-decl
spec:
  region: us-east-1
  availabilityZone: us-east-1a
  adminSecret:
    secretName: cluster-admin
    key: admin-json   