apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: auto-import-secret
spec:
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: crossplane
        serviceAccount:
          name: default
      name: kubeconfig
      path: crossplane-secrets/data/aro-tf
  output:
    name: auto-import-secret
    stringData:
      kubeconfig: '{{ .kubeconfig.kubeconfig }}'
      autoImportRetry: "10"
    type: Opaque    
  refreshPeriod: 3m0s