apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aro-decl

resources:
- ./namespace.yaml
- ./aro.yaml
- ./auto-import-secret.yaml

helmGlobals:
  chartHome: ../../../../helm/charts

helmCharts:
  - name: cluster-registration
    releaseName: aro-decl
    namespace: aro-decl
    valuesInline: 
      clusterSet: default
      repoURL: https://github.com/raffaelespazzoli/openshift-iac-multicluster.git
      labels:
        cloud: Aro
        vendor: OpenShift       