apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-cluster-management-observability

resources:
  - ./namespace.yaml
  - ./patches-rbac.yaml
  - ./patches.yaml
  - ./storage-secret.yaml
  - ./bucket-claim.yaml
  - ./multicluster-observability.yaml