kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-observability-patches-rbac
  namespace: stackrox
subjects:
  - kind: ServiceAccount
    name: default
    namespace: open-cluster-management-observability # namespace:operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io