apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: acs-patches
  namespace: open-cluster-management-observability
spec:
  serviceAccountRef:
    name: default
  patches:
    thanos-bucket-patch:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: open-cluster-management-observability
        name: thanos-object-storage
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: open-cluster-management-observability
        name: acm-observability-bucket
      - apiVersion: v1
        kind: ConfigMap
        namespace: open-cluster-management-observability
        name: acm-observability-bucket                
      patchTemplate: |
        {{ $content := print "type: s3\n" "config:\n" "  bucket: " (index (index . 2).data "BUCKET_NAME") "\n" "  endpoint:  " (index (index . 2).data "BUCKET_HOST") "\n" "  insecure: true\n" "  access_key: " ((index (index . 1).data "AWS_ACCESS_KEY_ID") | b64dec) "\n" "  secret_key: " ((index (index . 1).data "AWS_SECRET_ACCESS_KEY") | b64dec) }}
        data:
          thanos.yaml: {{ $content | b64enc }}
      patchType: application/merge-patch+json