{{ if .Values.automaticHostBinding }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-patches-rbac-{{ .Release.Name }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "cluster-deployment.labels" . | nindent 4 }}  
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
{{ end }}  