kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patches-rbac-{{ .Release.Namespace }}-{{ .Release.Name }}
  labels:
    {{- include "infra-env.labels" . | nindent 4 }}    
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io