kind: Secret
apiVersion: v1
metadata:
  name: pull-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infra-env.labels" . | nindent 4 }}  
data:
  '.dockerconfigjson': eyJhdXRocyI6eyJub3RoaW5nLmNvbSI6eyJhdXRoIjoiWTJsaGJ3PT09PSIsImVtYWlsIjoiZmFrZUBjaWFvLmNvbSJ9fX0=
type: 'kubernetes.io/dockerconfigjson'