---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capi-provider-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infra-env.labels" . | nindent 4 }}  
rules:
  - verbs:
      - '*'
    apiGroups:
      - agent-install.openshift.io
    resources:
      - agents
