---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/nfs-provisioner-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: "alpha"
    target:
      kind: Subscription
