---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/namespace-configuration-config/

patches:
  - patch: |-
      - op: replace
        path: /spec/templates/0/objectTemplate
        value: |
          apiVersion: redhatcop.redhat.io/v1alpha1
          kind: Policy
          metadata:
            name: secret-reader-{{ .Labels.cmdbID }}
            namespace: vault-admin
          spec:
            # Add fields here
            authentication: 
              path: kubernetes
              role: policy-admin
            policy: |
              # Read permission on the secrets
              path "/root/hub/applications/{{ .Labels.cmdbID }}/{{identity.entity.aliases.${auth/<cluster>/kubernetes/@accessor}.metadata.service_account_namespace}}/*" {
                  capabilities = ["read", "list"]
              }        
    target:
      kind: NamespaceConfig
      name: kube-vault-configs      
  - patch: |-
      - op: replace
        path: /spec/templates/0/objectTemplate
        value: |
          apiVersion: redhatcop.redhat.io/v1alpha1
          kind: Policy
          metadata:
            name: secret-writer-{{ .Labels.cmdbID }}
            namespace: vault-admin
          spec:
            # Add fields here
            authentication: 
              path: kubernetes
              role: policy-admin
            policy: |
              # Write permission on the secrets
              path "/root/hub/applications/{{ .Labels.cmdbID }}/*" {
                  capabilities = ["list", "create", "update", "delete"]
              }        
    target:
      kind: NamespaceConfig
      name: kube-vault-configs
  - patch: |-
      - op: replace
        path: /spec/templates/0/objectTemplate
        value: |
          apiVersion: redhatcop.redhat.io/v1alpha1
          kind: SecretEngineMount
          metadata:
            name: static-secrets-{{ .Labels.app }}
            namespace: vault-admin
          spec:
            authentication: 
              path: kubernetes
              role: kv-engine-admin
            type: /root/hub/applications/{{ .Labels.cmdbID }}/{{ .Name }}
            path: test-vault-config-operator        
    target:
      kind: NamespaceConfig
      name: tenant-secret-mounts           
