---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/namespace-configuration-config/

patches:
  - patch: |-
      - op: replace
        path: /spec/templates/0/objectTemplate
        value: |
          apiVersion: redhatcop.redhat.io/v1alpha1
          kind: Policy
          metadata:
            name: secret-reader-{{ .Labels.cmdbID }}
            namespace: vault-admin
          spec:
            # Add fields here
            authentication: 
              path: kubernetes
              role: policy-admin
              serviceAccount:
                name: default              
            policy: |
              # Read permission on the secrets
              path "/root/hub/applications/{{ .Labels.cmdbID }}/{{ {{ }} identity.entity.aliases.${auth/hub/kubernetes/@accessor}.metadata.service_account_namespace {{ }} }}/*" {
                  capabilities = ["read", "list"]
              }        
    target:
      kind: NamespaceConfig
      name: kube-vault-configs      
  - patch: |-
      - op: replace
        path: /spec/templates/0/objectTemplate
        value: |
          apiVersion: redhatcop.redhat.io/v1alpha1
          kind: Policy
          metadata:
            name: secret-writer-{{ .Labels.cmdbID }}
            namespace: vault-admin
          spec:
            # Add fields here
            authentication: 
              path: kubernetes
              role: policy-admin
              serviceAccount:
                name: default              
            policy: |
              # Write permission on the secrets
              path "/root/hub/applications/{{ .Labels.cmdbID }}/*" {
                  capabilities = ["list", "create", "update", "delete"]
              }
      - op: replace
        path: /spec/templates/2/objectTemplate
        value: |
          apiVersion: redhatcop.redhat.io/v1alpha1
          kind: GroupAlias
          metadata:
            name: prefix.{{ .Labels.cmdbID }}.secretsetter
            namespace: vault-admin
          spec:
            authentication: 
              path: kubernetes
              role: policy-admin
              serviceAccount:
                name: default              
            authEngineMountPath: hub/okta
            groupName: prefix.{{ .Labels.cmdbID }}.secretsetter                


                   
    target:
      kind: NamespaceConfig
      name: okta-vault-configs
  - patch: |-
      - op: replace
        path: /spec/templates/0/objectTemplate
        value: |
          apiVersion: redhatcop.redhat.io/v1alpha1
          kind: SecretEngineMount
          metadata:
            name: static-secrets-{{ .Labels.app }}
            namespace: vault-admin
          spec:
            authentication: 
              path: kubernetes
              role: policy-admin
              serviceAccount:
                name: default              
            type: kv
            path: /root/hub/applications/{{ .Labels.cmdbID }}/{{ .Name }}       
    target:
      kind: NamespaceConfig
      name: tenant-secret-mounts           
