---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: pool4-controller1.practice.redhat.com
    bmac.agent-install.openshift.io/role: master
  labels:
    infraenvs.agent-install.openshift.io: pool4
    cluster-name: pool4
  name: pool4-controller1.practice.redhat.com
  namespace: pool4
spec:
  automatedCleaningMode: metadata
  bmc:
    address: "idrac-virtualmedia://10.1.177.41/redfish/v1/Systems/System.Embedded.1"
    credentialsName: pool4-drac-credentials
    disableCertificateVerification: true
  bootMACAddress: E4:43:4B:4F:45:C9
  online: false
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: pool4-controller2.practice.redhat.com
    bmac.agent-install.openshift.io/role: master
  labels:
    infraenvs.agent-install.openshift.io: pool4
    cluster-name: pool4
  name: pool4-controller2.practice.redhat.com
  namespace: pool4
spec:
  automatedCleaningMode: metadata
  bmc:
    address: "idrac-virtualmedia://10.1.177.42/redfish/v1/Systems/System.Embedded.1"
    credentialsName: pool4-drac-credentials
    disableCertificateVerification: true
  bootMACAddress: 78:AC:44:38:30:FD
  online: false
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: pool4-controller3.practice.redhat.com
    bmac.agent-install.openshift.io/role: master
  labels:
    infraenvs.agent-install.openshift.io: pool4
    cluster-name: pool4
  name: pool4-controller3.practice.redhat.com
  namespace: pool4
spec:
  automatedCleaningMode: metadata
  bmc:
    address: "idrac-virtualmedia://10.1.177.43/redfish/v1/Systems/System.Embedded.1"
    credentialsName: pool4-drac-credentials
    disableCertificateVerification: true
  bootMACAddress: E4:43:4B:4E:3F:8D
  online: false
---  
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: pool4-compute1.practice.redhat.com
    bmac.agent-install.openshift.io/role: worker
  labels:
    infraenvs.agent-install.openshift.io: pool4
    cluster-name: pool4
  name: pool4-compute1.practice.redhat.com
  namespace: pool4
spec:
  automatedCleaningMode: metadata
  bmc:
    address: "idrac-virtualmedia://10.1.177.44/redfish/v1/Systems/System.Embedded.1"
    credentialsName: pool4-drac-credentials
    disableCertificateVerification: true
  bootMACAddress: E4:43:4B:4E:40:35
  online: false
---  
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: pool4-compute2.practice.redhat.com
    bmac.agent-install.openshift.io/role: worker
  labels:
    infraenvs.agent-install.openshift.io: pool4
    cluster-name: pool4
  name: pool4-compute2.practice.redhat.com
  namespace: pool4
spec:
  automatedCleaningMode: metadata
  bmc:
    address: "idrac-virtualmedia://10.1.177.45/redfish/v1/Systems/System.Embedded.1"
    credentialsName: pool4-drac-credentials
    disableCertificateVerification: true
  bootMACAddress: E4:43:4B:4E:3B:D5
  online: false  