apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pool4-infra
resources:  
  - ./namespace.yaml
  - ./infra-env.yaml
  - ./patches-rbac.yaml
  - ./patches.yaml
  - ./pull-secret.yaml
  - ./role.yaml
  - ./baremetal-hosts.yaml
  #- ./drac-credentials-secret.yaml