apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: pool4-pull-secret-patch
spec:
  serviceAccountRef:
    name: default
  patches:
    pull-secret-patch:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: pool4
        name: pullsecret-pool4
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: openshift-config
        name: pull-secret                
      patchTemplate: |
        data:
          .dockerconfigjson: {{ (index (index . 1).data ".dockerconfigjson") }}
      patchType: application/merge-patch+json