apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: rook-ceph-bucket
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true  
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteOnce
    volumeMode: 
      Filesystem
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: rook-cephfs
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true  
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode:
      Filesystem
  cloneStrategy: csi-clone
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:  
  name: rook-nfs
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true  
spec: 
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode:
      Filesystem