
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-config

secretGenerator:
- name: htpass-secret
  files:
  - htpasswd

resources:
  - ./oauth.yaml
  - ./admin-role-binding.yaml

generatorOptions:
 disableNameSuffixHash: true  