apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-manager
spec: {}
---    
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cert-manager
  source: community-operators
  sourceNamespace: openshift-marketplace