apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    {{- with .Values.labels }}
    .
    {{- end }}
    name: {{ .Release.Name }}
    cluster.open-cluster-management.io/clusterset: 'default'
    {{- include "cluster-registration.labels" . | nindent 4 }}
  name: {{ .Release.Name }}  
spec:
  hubAcceptsClient: true