apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xrosas.crossplane.redhat-cop.com
spec:
  group: crossplane.redhat-cop.com
  defaultCompositeDeletePolicy: Foreground
  defaultCompositionUpdatePolicy: Automatic
  names:
    kind: xRosa
    plural: xrosas
  claimNames:
    kind: Rosa
    plural: rosas    
  versions:
  - name: v1alpha1
    served: true
    referenceable: true  
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                description: "AWS region"
                type: string
            required: 
              - region                