apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rosa
spec:
  compositeTypeRef:
    apiVersion: crossplane.redhat-cop.com/v1alpha1
    kind: xRosa
  patchSets:
  - name: availabilityZone
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.availabilityZone"
      toFieldPath: "spec.forProvider.availabilityZone"  
  - name: region
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.region"
  - name: name-tag
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.tags.Name"            
  resources:
  - name: vpc
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: VPC
      metadata:
        name: rosa-vpc
      spec:
        forProvider:
          cidrBlock: 10.0.0.0/16
          enableDnsHostnames: true
          enableDnsSupport: true
          region: replace
          tags:
            Name: replace
    patches:
      - type: PatchSet
        patchSetName: region
      - type: PatchSet
        patchSetName: name-tag
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: public-egress-subnet
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: rosa-public-egress
        labels:
          public-subnet: ""
      spec:
        forProvider:
          cidrBlock: 10.0.128.0/17
          region: replace
          tags:
            Name: replace          
          vpcIdSelector:
            matchControllerRef: true
          availabilityZone: replace  
    patches:
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: metadata.name
          strategy: string
          string:
            fmt: "%s-public-egress"
        toFieldPath: spec.forProvider.tags.Name    
      - type: PatchSet
        patchSetName: region
      - type: PatchSet
        patchSetName: availabilityZone        
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: private-internal-subnet
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: rosa-private-internal
        labels:
          private-subnet: ""
      spec:
        forProvider:
          cidrBlock: 10.0.0.0/17
          region: replace
          tags:
            Name: replace          
          vpcIdSelector:
            matchControllerRef: true
          availabilityZone: replace  
    patches:
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: metadata.name
          strategy: string
          string:
            fmt: "%s-private-internal"
        toFieldPath: spec.forProvider.tags.Name    
      - type: PatchSet
        patchSetName: region
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.id
        toFieldPath: "status.subnets.privateSubnetID"
        policy:
          fromFieldPath: Optional
      - type: PatchSet
        patchSetName: availabilityZone                  
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: internet-gateway
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: InternetGateway
      metadata:
        name: rosa-internet-gateway
      spec:
        forProvider:
          region: replace
          tags:
            Name: replace
          vpcIdSelector:
            matchControllerRef: true
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: public-route-table
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTable
      metadata:
        name: public-rosa-route-table
        labels:
          public-route-table: ""        
      spec:
        forProvider:
          region: replace
          tags:
            Name: replace
          vpcIdSelector:
            matchControllerRef: true
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition        
  - name: egress-route
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Route
      metadata:
        name: rosa-egress-route
      spec:
        forProvider:
          destinationCidrBlock: 0.0.0.0/0
          gatewayIdSelector:
            matchControllerRef: true
          region: replace
          tags:
            Name: replace          
          routeTableIdSelector:
            matchLabels:
              public-route-table: ""              
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: public-route-table-association
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTableAssociation
      metadata:
        name: public-rosa-route-table-association
      spec:
        forProvider:
          region: replace
          tags:
            Name: replace          
          routeTableIdSelector:
            matchLabels:
              public-route-table: ""
          subnetIdSelector:
            matchLabels:
              public-subnet: ""
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: elastic-ip
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: EIP
      metadata:
        name: rosa-elastic-ip
      spec:
        forProvider:
          tags:
            Name: replace        
          region: replace
          vpc: true
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: nat-gateway
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: NATGateway
      metadata:
        name: rosa-nat-gateway
      spec:
        forProvider:
          region: replace
          tags:
            Name: replace          
          subnetIdSelector:
            matchLabels:
              public-subnet: ""
          allocationIdSelector:
            matchControllerRef: true              
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: private-route-table
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTable
      metadata:
        name: private-rosa-route-table
        labels:
          private-route-table: ""        
      spec:
        forProvider:
          region: replace
          tags:
            Name: replace
          vpcIdSelector:
            matchControllerRef: true
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition        
  - name: nat-egress-route
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Route
      metadata:
        name: rosa-nat-egress-route
      spec:
        forProvider:
          destinationCidrBlock: 0.0.0.0/0
          natGatewayIdSelector:
            matchControllerRef: true
          region: replace
          tags:
            Name: replace          
          routeTableIdSelector:
            matchLabels:
              private-route-table: ""
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: private-route-table-association
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTableAssociation
      metadata:
        name: private-rosa-route-table-association
      spec:
        forProvider:
          region: replace
          tags:
            Name: replace          
          routeTableIdSelector:
            matchLabels:
              private-route-table: ""
          subnetIdSelector:
            matchLabels:
              private-subnet: ""
    patches:
      - type: PatchSet
        patchSetName: name-tag
      - type: PatchSet
        patchSetName: region
    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition
  - name: rosa
    base:
      apiVersion: tf.upbound.io/v1beta1
      kind: Workspace
      metadata:
        name: rosa
      spec:
        publishConnectionDetailsTo:
          name: rosa-tf
          configRef:
            name: vault      
        forProvider:
          # Use any module source supported by terraform init -from-module.
          source: Remote
          module: git::https://github.com/raffaelespazzoli/openshift-iac-multicluster//terraform/rosa
          # Variables can be specified inline as a list of key-value pairs or as an json object, or loaded from a ConfigMap or Secret.
          vars:
          - key: operator_role_prefix
            value: ""
          - key: account_role_prefix
            value: ""
          - key: cluster_name
            value: ""         
          - key: cloud_region
            value: ""
          - key: aws_subnet_id
            value: ""  
          - key: availability_zone
            value: ""                       
          varFiles:  
          - secretKeyRef:
              key: key
              name: name
              namespace: namespace
            source: SecretKey
            format: JSON                            
    patches: 

    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: metadata.name
        strategy: string
        string:
          fmt: "%s-operator"
      toFieldPath: spec.forProvider.vars[0].value

    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: metadata.name
        strategy: string
        string:
          fmt: "%s-account"
      toFieldPath: spec.forProvider.vars[1].value

    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.vars[2].value"      

    - type: FromCompositeFieldPath
      fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.vars[3].value" 

    - type: FromCompositeFieldPath
      fromFieldPath: "status.subnets.privateSubnetID"
      toFieldPath: "spec.forProvider.vars[4].value"
      policy:
        fromFieldPath: Required

    - type: FromCompositeFieldPath
      fromFieldPath: "spec.availabilityZone"
      toFieldPath: "spec.forProvider.vars[5].value"                               

    - type: FromCompositeFieldPath
      fromFieldPath: "spec.adminSecret.secretName"
      toFieldPath: "spec.forProvider.varFiles[0].secretKeyRef.name"

    - type: FromCompositeFieldPath
      fromFieldPath: "spec.adminSecret.key"
      toFieldPath: "spec.forProvider.varFiles[0].secretKeyRef.key"

    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.labels['crossplane.io/claim-namespace']"
      toFieldPath: "spec.forProvider.varFiles[0].secretKeyRef.namespace"            

    readinessChecks:	
      - matchCondition:	
          status: 'True'	
          type: Ready	
        type: MatchCondition                                                                                                                      