apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: 'pool4'
  namespace: 'pool4'
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: vinny-lab
spec:
  clusterDeploymentRef:
    name: 'pool4'
  holdInstallation: true
  provisionRequirements:
    workerAgents: 2
    controlPlaneAgents: 3
  imageSetRef:
    name: 'img4.13.9-multi-appsub'
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
    machineNetwork:
    - cidr: 10.1.196.41/27
    userManagedNetworking: false
  ingressVIP: 10.1.196.48
  apiVIP: 10.1.196.49  