apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pool4
resources:  
  - ./agent-cluster-install.yaml
  - ./cluster-deployment.yaml
  - ./klusterlet-config.yaml
  - ./managed-cluster.yaml