apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: agent-patches
spec:
  serviceAccountRef:
    name: default
  patches:
    agents-patch:
      targetObjectRef:
        apiVersion: agent-install.openshift.io/v1beta1
        kind: Agent
        namespace: pool4-infra
        labelSelector:
          matchExpressions:
            - key: agent-install.openshift.io/bmh
              operator: In
              values:
              - pool4-compute1.practice.redhat.com
              - pool4-compute2.practice.redhat.com
              - pool4-controller1.practice.redhat.com
              - pool4-controller2.practice.redhat.com
              - pool4-controller3.practice.redhat.com
      patchTemplate: |
        spec:
          clusterDeploymentName:
            name: pool4
            namespace: pool4
      patchType: application/merge-patch+json
    pull-secret-patch:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: pool4
        name: pullsecret-pool4
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: openshift-config
        name: pull-secret                
      patchTemplate: |
        data:
          .dockerconfigjson: {{ (index (index . 1).data ".dockerconfigjson") }}
      patchType: application/merge-patch+json      