kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab4-cluster-patches-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: pool4-cluster # namespace:operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io