---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-admin
resources:
  - ./namespace.yaml
  - ./kube-auth-engine-config.yaml
  - ./kube-auth-engine-mount.yaml
  - ./okta-auth-engine-mount.yaml
  - ./okta-auth-engine-config.yaml
  - ./okta-auth-engine-role.yaml  