apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuthEngineMount
metadata:
  name: okta
spec:
  authentication: 
    path: kubernetes
    role: policy-admin
  type: oidc
  path: <cluster>
  local: false