apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineRole
metadata:
  name: vault-developer
spec:
  authentication: 
    path: kubernetes
    role: policy-admin
  path: <cluster>/okta
  boundAudiences: 
  - "0oaau92rizgjZ2l935d7"
  name: vault-developer
  userClaim: "sub"
  allowedRedirectURIs: 
    - "http://localhost:8250/oidc/callback"
    - "http://<vault_addr>/ui/vault/auth/oidc/oidc/callback"
  groupsClaim: "groups" 
  tokenPolicies: 
    - "default"
  roleType: "oidc"
  OIDCScopes: 
    - "groups"