apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/ansible-automation-platform-operator/
commonAnnotations:
  argocd.argoproj.io/sync-options: Delete=false

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: "stable-2.4-cluster-scoped"
    target:
      kind: Subscription