apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: okta-vault-configs
spec:
  labelSelector:
    matchExpressions:
      - key: cmdbID
        operator: Exists
  templates:     
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: SecretEngineMount
        metadata:
          name: static-secrets
        spec:
          authentication: 
            path: kubernetes
            role: kv-engine-admin
          type: /root/<cluster>/applications/{{ .Labels.cmdbID }}/{{ .Name }}
          path: test-vault-config-operator                    