kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab4-infra-patches-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io